# Generated by Django 6.0.5 on 2026-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('in_process', 'Em Processamento'), ('refunded', 'Estornado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Aguardando Pagamento'), ('received', 'Pedido Recebido'), ('preparing', 'Em Preparo'), ('delivery', 'Saiu para Entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=20),
        ),
    ]
